### ISSUE TITLE
Leer la doc de materialize

### ISSUE THREAD

**Issue by roadev** [roadev/rifa#1]
Leer lo básico para la implementación de materialize y los components.
http://materializecss.com

**Comment by dianahernandez** [comment]
explicación de la exponencial 2**999999? y de porqué odian a python3

**Comment by roadev** [comment]
Eso no tiene nada que ver con esta issue...
Crea una para ese problema
Aquí comentas lo relacionado a esta issue (la lectura de materialize, que espero, ya estés haciendo...)

**Comment by roadev** [comment]
Tenés huevo Caro xD

**Comment by roadev** [comment]
Cierro issue....
Ya leí lo que necesitaba.
